### ISSUE TITLE
modifyVars appears to be changing in the less-loader

### ISSUE THREAD

**Issue by Steven-Lilley-Imprivata** [letshare/storybook-addon-customize-antd-theme#1]
And seem to be throwing errors...
The proposed adjustments seem to be discussed here: https://github.com/webpack-contrib/less-loader/issues/303
![Screenshot (53)](https://user-images.githubusercontent.com/94488581/150548705-250119b7-cd7d-44fb-bd5c-55664ce84632.png)

**Comment by gidich** [comment]
Seeing the same thing - tried a number of things to get around it but no luck so far.  

update 2/5/2022 - may have a fix - will post here ..

**Comment by letshare** [comment]
@gidich @Steven-Lilley-Imprivata  This addon does not rely on less loader. You can remove the use of modifyVars in the project build configuration. If you need to use it, please ensure that the use method is consistent with the less loader version. Please refer to https://ant.design/docs/react/customize-theme

**Comment by letshare** [comment]
> And seem to be throwing errors... The proposed adjustments seem to be discussed here: [webpack-contrib/less-loader#303](https://github.com/webpack-contrib/less-loader/issues/303) ![Screenshot (53)](https://user-images.githubusercontent.com/94488581/150548705-250119b7-cd7d-44fb-bd5c-55664ce84632.png)

Errors in addon will not appear in canvas. In addition, storybook-addon-customise-antd-theme does not use less-loader. It seems that modifyVars is used in your stories file. Can you let me see where you use modifyVars? What is your storybook version？

**Comment by letshare** [comment]
No further feedback, I'll close first
